### ISSUE TITLE
Improvement of the responsiveness of the apply form

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#20]
<h2 align="center">Issue picture</h2>
<div align="center">
<p> Making the application form responsive </p>
<img src="https://cdn.discordapp.com/attachments/791743706402652170/891041624979808356/unknown.png" height="300px">
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>
</div>

**Comment by RepeaterCreeper** [comment]
Hi, this is would be my first contribution. Would I need to wait until October to make this count towards hacktoberfest? I would like to take a stab at this.

**Comment by pulkithanda** [comment]
Hey! @RepeaterCreeper You can start working on it now but submit the PR in October that way it will count for hacktoberfest. Assigned the issue to you, I f you face any problem contact me on discord.

**Comment by RepeaterCreeper** [comment]
> Hey! @RepeaterCreeper You can start working on it now but submit the PR in October that way it will count for hacktoberfest. Assigned the issue to you, If you face any problem contact me on discord. Also you know right how to contribute forking the repository then pushing changes to it and submitting a PR ?

I don't have experience doing it, but I've seen the Hacktoberfest Guide and additionally I have to add my name to the `contributors.md` and the issue I fixed.

**Comment by pulkithanda** [comment]
Any updates yet @RepeaterCreeper  ?

**Comment by Raghav-Modani** [comment]
Hey @pulkithanda! Can I work on this issue?

**Comment by pulkithanda** [comment]
Hey there @Raghav-Modani Sure go ahead

**Comment by Raghav-Modani** [comment]
Hello @pulkithanda! While running the command `flask run` I am getting this error :
PS D:\HacktoberFest2021\hacktoberfest7\voyager-hf\voyager> flask run 
 * Serving Flask app '__init__' (lazy loading)
 * Environment: development
 * Debug mode: on
Try 'flask run --help' for help.

Error: While importing 'voyager', an ImportError was raised:

Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 256, in locate_app
    __import__(module_name)
  File "D:\HacktoberFest2021\hacktoberfest7\voyager-hf\voyager\__init__.py", line 3, in <module>
    from flask_bcrypt import Bcrypt
ModuleNotFoundError: No module named 'flask_bcrypt'

What should I do to run the app on localhost?

**Comment by pulkithanda** [comment]
Hey @Raghav-Modani I have all the list of modules in requirements.txt so just install that and then run. There's a command pip install equirements.txt to do all you can check it out on google. just install requirements then run.

**Comment by Raghav-Modani** [comment]
> Hey @Raghav-Modani I have all the list of modules in requirements.txt so just install that and then run. There's a command pip install equirements.txt to do all you can check it out on google. just install requirements then run.

I have already done this. All other packages like SQLAlchemy, Flask-login etc are working fine. Only this flask-bcrypt is not resolving.

**Comment by pulkithanda** [comment]
Hmm I see maybe git pull once and then try? It'll work then I tried right now. If there's still an import error then do tell.
